<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Accept</name>
   <tag></tag>
   <elementGuidId>6e93f83b-bcb6-4550-a303-f1695b36309b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_ucApprove_btnAuditAccept']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_ucApprove_btnAuditAccept</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a5d2e66-0d45-4971-8f9a-b41ea6f47e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b32e4558-41cc-45b3-bfae-36e674ebf246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ucApprove$btnAuditAccept</value>
      <webElementGuid>abd846eb-9283-4928-8f55-36b3458587bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Accept</value>
      <webElementGuid>18c4ba11-6bd8-4ebd-945f-677cae7381c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return validate('ctl00_ContentPlaceHolder1_ucApprove_GvAuditArea','Audit Area master','Accept',this);</value>
      <webElementGuid>ae84b057-0ccb-44d3-82a9-5cefee09608d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_ucApprove_btnAuditAccept</value>
      <webElementGuid>025c3004-6873-4a5b-a61b-46a66e0aff61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>37418956-6a2a-4825-9870-900ded46d48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_ucApprove_btnAuditAccept&quot;)</value>
      <webElementGuid>c54052ae-e605-4346-9a04-2f07c07b05f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_ucApprove_btnAuditAccept']</value>
      <webElementGuid>5ee656c1-f6eb-46e3-aa3d-b7cff645e454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_ContentPlaceHolder1_ucApprove_TR_AuditArea']/td/table/tbody/tr[2]/td/table/tbody/tr[4]/td/input[2]</value>
      <webElementGuid>dae09cee-7e47-4c70-9087-aea297a995fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input[2]</value>
      <webElementGuid>a66f82fd-e6e1-4609-a65f-bc20fe7d1d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder1$ucApprove$btnAuditAccept' and @id = 'ctl00_ContentPlaceHolder1_ucApprove_btnAuditAccept']</value>
      <webElementGuid>0be78569-b25a-43fa-8172-d5b867e299da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
