<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>approve</name>
   <tag></tag>
   <elementGuidId>066c5dc1-d433-4407-ae51-4e4d65f14896</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='Image4n']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;Image4n&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a2bac7e5-1e83-440c-b19d-71df2bbc3230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/btn/approve-on.gif</value>
      <webElementGuid>ba8f32a4-2e22-4754-b80e-e46d2f9d7a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Image4n</value>
      <webElementGuid>b6c5705e-92f5-4b69-a79b-0f730c5034ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c8f12b3e-f3d0-433e-934c-4a8af047faac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Stm0p0i8eTX&quot;)/table[1]/tbody[1]/tr[1]/td[1]/a[1]/img[1]</value>
      <webElementGuid>5a2dbdbe-fb31-48c0-9c9d-5b301a86128c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='Image4n']</value>
      <webElementGuid>a8fda671-6869-4b80-8128-dc03326e868e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//font[@id='Stm0p0i8eTX']/table/tbody/tr/td/a/img</value>
      <webElementGuid>9551227b-ae1a-4ccd-a080-4a5ecc5d12b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/a/div/table/tbody/tr/td/font/table/tbody/tr/td/a/img</value>
      <webElementGuid>1c029e6f-6314-4b90-9fe5-9f3c5db9fab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/btn/approve-on.gif' and @name = 'Image4n']</value>
      <webElementGuid>ec8dd22d-dd29-4c12-8ffe-724dae556db4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
