<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>audit_planning</name>
   <tag></tag>
   <elementGuidId>fa47b34a-363a-47e3-b9fb-84e5ce2abdc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='Image2p']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;Image2p&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>25a61233-385f-4846-b252-f3adfea3c499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/btn/auditplanning-on.gif</value>
      <webElementGuid>da8e8e11-e5ed-42ba-8754-f5d72db4fa57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Image2p</value>
      <webElementGuid>4f8debef-b75b-4628-b955-69da10b672ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bb9e35d6-40ac-48ec-a3dc-bd363c6b7271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Stm0p0i2eTX&quot;)/table[1]/tbody[1]/tr[1]/td[1]/a[1]/img[1]</value>
      <webElementGuid>37c5cdac-d16e-4c91-b0f9-c7dab21d5aa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='Image2p']</value>
      <webElementGuid>2bb895fe-639c-4660-a2a8-16e39918dc74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//font[@id='Stm0p0i2eTX']/table/tbody/tr/td/a/img</value>
      <webElementGuid>45a53ed8-0611-4ed9-8e6e-021332d1c008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a/div/table/tbody/tr/td/font/table/tbody/tr/td/a/img</value>
      <webElementGuid>df37a53e-73ae-442a-9b67-7d434551cd14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/btn/auditplanning-on.gif' and @name = 'Image2p']</value>
      <webElementGuid>f8322161-c6cb-45e3-b6dc-8c6b9d2fd38f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
