<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>auditee_icon</name>
   <tag></tag>
   <elementGuidId>c8f6a808-8b31-4d55-8a85-fcb5f6fad2c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form1']/table/tbody/tr[2]/td/table/tbody/tr[4]/td/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>68fa3de4-b37b-4185-b60e-6abc2f96a9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/ico/pick_user.gif</value>
      <webElementGuid>3ad1540d-4464-478d-b044-d28425bf12d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>9df31ad0-e405-4461-ad2a-7fc34d2386f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>41ed84dd-27c9-4455-81d9-874a0b28710b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7eb5bab0-0f06-4364-b037-7054529acb08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c369b128-7cff-426a-8226-361296c1e9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>absbottom</value>
      <webElementGuid>fe9dd103-1db1-43a9-8e17-5d5476c3f51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/table[@class=&quot;default&quot;]/tbody[1]/tr[2]/td[1]/table[@class=&quot;default&quot;]/tbody[1]/tr[4]/td[1]/a[1]/img[1]</value>
      <webElementGuid>ada7da90-08de-4eec-90ba-8f43615c32fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/table/tbody/tr[2]/td/table/tbody/tr[4]/td/a/img</value>
      <webElementGuid>b1475eee-ce5e-4cc7-beb2-2c70fc70f26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>aa0b49f0-c1e5-489b-8298-f19e4f2bcd38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/ico/pick_user.gif']</value>
      <webElementGuid>402ad6ce-5572-420e-b04a-e3fbe71576c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
