<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AUDITORS_workspace_tab</name>
   <tag></tag>
   <elementGuidId>9974daef-2ade-4e7c-ae4f-5fb7062995b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;Image2n&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='Image2n']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>33a2cb67-0209-46dc-aa09-4d0813e628f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/btn/auditorsworkspace-on.gif</value>
      <webElementGuid>a5410de3-ef78-4fc9-a35c-7b234e5b6990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Image2n</value>
      <webElementGuid>4332550e-8bde-475c-9991-116b6b5ff504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d5edafed-2108-4850-95f9-49ba6ed7f5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Stm0p0i4eTX&quot;)/table[1]/tbody[1]/tr[1]/td[1]/a[1]/img[1]</value>
      <webElementGuid>f9697322-befc-4698-9ce8-30153d906cd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='Image2n']</value>
      <webElementGuid>fa2e0a1d-3978-4740-9522-5b8dbfd4b400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//font[@id='Stm0p0i4eTX']/table/tbody/tr/td/a/img</value>
      <webElementGuid>9aabe020-2022-4508-bd23-f7b1e2f3b6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a/div/table/tbody/tr/td/font/table/tbody/tr/td/a/img</value>
      <webElementGuid>7ef21c1f-70d4-4520-a1c1-949f9ece3e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/btn/auditorsworkspace-on.gif' and @name = 'Image2n']</value>
      <webElementGuid>8b021ef7-9625-472d-ae93-016b60577636</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
