<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Audits Un-locked Successfully</name>
   <tag></tag>
   <elementGuidId>799f2427-3782-4807-b542-09ac2980637f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_ContentPlaceHolder1_lblMessage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_lblMessage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2b13b544-05c2-403b-815a-901e74435710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_lblMessage</value>
      <webElementGuid>aa10696a-fe6e-4691-8232-46362cc42b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>redcontent</value>
      <webElementGuid>f54c7a2e-77eb-4568-81d9-e45d17ac0779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Audits Un-locked Successfully.</value>
      <webElementGuid>62a3772c-8efd-41c8-be65-30e3eda7a93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_lblMessage&quot;)</value>
      <webElementGuid>9f7402a5-63d1-4362-bbb9-09cab5d84a13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ContentPlaceHolder1_lblMessage']</value>
      <webElementGuid>cf2b03eb-ed10-4b55-ae31-4479e3fc6c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/table/tbody/tr/td/table/tbody/tr[3]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr[2]/td/span</value>
      <webElementGuid>e3beb0dd-eec6-4133-a66a-32c66940e3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[20]/following::span[1]</value>
      <webElementGuid>48394958-78cd-4042-9b47-3df91d7eae77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location :'])[1]/following::span[2]</value>
      <webElementGuid>44288c36-0375-4361-b17a-02f17c90081d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing Results 0 to 0 of 0'])[1]/preceding::span[1]</value>
      <webElementGuid>9ece93f0-a303-4255-a120-0c59925b781d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LARS Version 2.0'])[1]/preceding::span[2]</value>
      <webElementGuid>a8d7ed3d-0e77-4f9c-af34-b6b126e7be66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Audits Un-locked Successfully.']/parent::*</value>
      <webElementGuid>d0fb4ab1-fcd5-4219-8ff6-d848bdc8b0dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/span</value>
      <webElementGuid>2f957580-4abf-4a96-9c2a-3ba9c23910b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_ContentPlaceHolder1_lblMessage' and (text() = 'Audits Un-locked Successfully.' or . = 'Audits Un-locked Successfully.')]</value>
      <webElementGuid>ee7c8b8e-f08d-419c-9031-39046a02e1e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
