<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>auto_fill_escalator</name>
   <tag></tag>
   <elementGuidId>23e03cb6-112a-46d8-9147-dc6ad8c87c9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ChkEsc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ChkEsc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f41ec4a0-0bb7-4fbb-b41f-80ca1c564cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ChkEsc</value>
      <webElementGuid>7233f7af-15c3-48c0-bd2b-b07a6c9c647c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2b25b6c1-5c90-4f73-94bd-f33849bd4c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ChkEsc</value>
      <webElementGuid>2f3540ee-c71b-47f3-88b4-17c923d9d265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ChkEsc\',\'\')', 0)</value>
      <webElementGuid>c7e688c5-b02a-4c4b-b6d5-a495759059ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ChkEsc&quot;)</value>
      <webElementGuid>9d7d9522-8a25-42af-adfd-be3fe670b89f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ChkEsc']</value>
      <webElementGuid>e85839c2-c45d-4cfe-b5db-1c0c39b007d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/table/tbody/tr[2]/td/table/tbody/tr[6]/td/input</value>
      <webElementGuid>b6e32957-2b5b-4b0f-a7e7-f07fab3e7bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/input</value>
      <webElementGuid>1a7cfc0d-6279-4571-b7de-0ba646028fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ChkEsc' and @type = 'checkbox' and @name = 'ChkEsc']</value>
      <webElementGuid>cd072766-d59d-4cdc-8d51-b53080a70cd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
