<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>change_lead_auditor_icon</name>
   <tag></tag>
   <elementGuidId>1675fa04-0af1-4443-9228-47da8e6a3e04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgChangeLeadAuditor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgChangeLeadAuditor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36b533b6-fb11-4af8-bd00-f3d9af9e089d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>5ebbd4c3-82e0-4cbd-8379-c960aecb1570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$gvSchQAudit$ctl02$imgChangeLeadAuditor</value>
      <webElementGuid>fe62b210-d979-4f3c-945f-d2a9606fbbbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgChangeLeadAuditor</value>
      <webElementGuid>6bca95b6-0480-4405-a199-f3c20340f3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Change Lead Auditor</value>
      <webElementGuid>232ba7e3-d115-43e7-a97b-74867db159b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/ico/change_request.gif</value>
      <webElementGuid>4942db86-4f76-477c-90a1-fcaba28e9de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgChangeLeadAuditor&quot;)</value>
      <webElementGuid>a8d390b2-8bd8-4001-b405-b4d276f083f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgChangeLeadAuditor']</value>
      <webElementGuid>c0d7ea0d-d922-4167-97b0-7dfaf4e19959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='demoTable']/tbody/tr[2]/td[11]/input</value>
      <webElementGuid>bfe88c54-c923-45eb-8885-cf8ebf2d5f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/input</value>
      <webElementGuid>357f8b14-b33b-4bad-a558-4d222585697c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$gvSchQAudit$ctl02$imgChangeLeadAuditor' and @id = 'ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgChangeLeadAuditor' and @title = 'Change Lead Auditor' and @src = 'images/ico/change_request.gif']</value>
      <webElementGuid>cb4b7a69-6e4e-4476-8ec7-72af2a756858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
