<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox</name>
   <tag></tag>
   <elementGuidId>c512dc83-41a6-4682-9fd3-a647bec05ee8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_ucApprove_GvAuditArea_ctl02_chk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_ucApprove_GvAuditArea_ctl02_chk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cab32a42-62e2-43bd-938b-e51d42f83f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ucApprove$GvAuditArea$ctl02$chk</value>
      <webElementGuid>0b7cb7ce-5690-45aa-9394-5bf54bb93c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>061f4278-b27c-4842-be7c-e28fe047f319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_ucApprove_GvAuditArea_ctl02_chk</value>
      <webElementGuid>5c59be0c-06f2-43b1-b233-14a872a155d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3906</value>
      <webElementGuid>c1689bb0-fb1b-463a-a27e-7934c7293b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_ucApprove_GvAuditArea_ctl02_chk&quot;)</value>
      <webElementGuid>99490793-ebcf-4161-9b30-8a48c9de8973</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_ucApprove_GvAuditArea_ctl02_chk']</value>
      <webElementGuid>ee089d0e-13f9-4ec3-a698-79d9cc1160b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_ucApprove_GvAuditArea']/tbody/tr[2]/td/input</value>
      <webElementGuid>777f31db-5150-4eb7-aa34-e59fc14bd8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>89ae256a-4f36-4b3b-9fc9-72a1d565d18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$ucApprove$GvAuditArea$ctl02$chk' and @type = 'checkbox' and @id = 'ctl00_ContentPlaceHolder1_ucApprove_GvAuditArea_ctl02_chk']</value>
      <webElementGuid>935dbd38-1b5e-4520-a220-df64ca6e3846</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
