<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_RE-ACTIVATE AUDIT AREA</name>
   <tag></tag>
   <elementGuidId>de11dfd8-1c6b-43bc-a9ad-92c00104cd2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_chkReActivateAudit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_chkReActivateAudit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>839fe7fd-c7fc-4797-a3bc-45cf8114e265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_chkReActivateAudit</value>
      <webElementGuid>1f01169e-0741-4623-8063-c3b705dda799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>94f51f70-e17a-459f-b4a9-13a6a21d3623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$chkReActivateAudit</value>
      <webElementGuid>2fbc6922-5a98-40de-84d7-651bdb300e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_chkReActivateAudit&quot;)</value>
      <webElementGuid>843b5117-9960-487e-b792-1ef2f3895716</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_chkReActivateAudit']</value>
      <webElementGuid>8fbee80d-b141-40e9-813f-e4dddedcffba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_pnlReActivateAudit']/table/tbody/tr[2]/td/table/tbody/tr/td/input</value>
      <webElementGuid>9a8ff114-028d-4b4f-8eb9-a2478c353522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/input</value>
      <webElementGuid>fc3889ae-22d9-442b-b3e3-d9377a7ab092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_ContentPlaceHolder1_chkReActivateAudit' and @type = 'checkbox' and @name = 'ctl00$ContentPlaceHolder1$chkReActivateAudit']</value>
      <webElementGuid>0be3abad-93c5-4e1d-8e4e-c490703c0805</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
