<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_audit_area</name>
   <tag></tag>
   <elementGuidId>542481d4-c17c-41b5-92f4-266802d224e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_gvAuditPlan_ctl04_chk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_gvAuditPlan_ctl04_chk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0662997c-fbfd-42c9-bf63-d4436f660afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_gvAuditPlan_ctl04_chk</value>
      <webElementGuid>04748001-f715-408a-a7ea-b446717b594f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dddcf44a-ca92-435a-8249-633e9577754f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$gvAuditPlan$ctl04$chk</value>
      <webElementGuid>10f5fb86-d233-4b54-972e-fbd5610086d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:DisplayNoTimesAudit(this,'ctl00_ContentPlaceHolder1_gvAuditPlan_ctl04_txtNoTimesAudit');</value>
      <webElementGuid>359fb727-19c0-4219-866a-2b2b6051c560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_gvAuditPlan_ctl04_chk&quot;)</value>
      <webElementGuid>2da743d7-8f84-4159-9d22-ee56071a9c10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_gvAuditPlan_ctl04_chk']</value>
      <webElementGuid>11e4e8ee-6da9-4b23-aed5-b22efb287b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='demoTable1']/tbody/tr[4]/td/input</value>
      <webElementGuid>0394f516-8509-4bf1-bfd7-91edfd758d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>9da4738f-0832-49f4-8faa-96b12450fc74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_ContentPlaceHolder1_gvAuditPlan_ctl04_chk' and @type = 'checkbox' and @name = 'ctl00$ContentPlaceHolder1$gvAuditPlan$ctl04$chk']</value>
      <webElementGuid>b1d8b4f0-e5d6-4550-9bb1-901742da3728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
