<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk</name>
   <tag></tag>
   <elementGuidId>642aa828-be76-4540-af55-394b50fc65c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='chk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;chk&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ba27f66-34dd-43d9-8c80-858f49c472c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>ad8a36f2-de8f-4677-b9e9-25e4997549b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ac9f42e6-cabf-41d9-a1c2-165fb25b29cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>7|Etrends ETD06</value>
      <webElementGuid>2f67c559-d3aa-4fd7-9c3b-88a47914570c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>chkAdd(this)</value>
      <webElementGuid>3729ee1e-964c-4d3a-95f9-02261a5604e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvUser&quot;)/tbody[1]/tr[@class=&quot;gridRow&quot;]/td[1]/input[1]</value>
      <webElementGuid>75c071b6-9566-4072-9df4-368016cf8f3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='chk']</value>
      <webElementGuid>0fff4de8-5567-4caa-88a4-642140fb38d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvUser']/tbody/tr[2]/td/input</value>
      <webElementGuid>6b49f110-32fd-44c5-bcac-c7f61073cda0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>e258dbe5-a29a-4133-8791-22850af528cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'chk' and @type = 'checkbox']</value>
      <webElementGuid>560a48da-9465-4176-9ec6-21661af4fd77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
