<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close_icon</name>
   <tag></tag>
   <elementGuidId>09c6df22-50c5-40c6-8042-d9dc191d7f1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='UserBox']/div/div/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[title=&quot;Close&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9102e6d4-0d3b-4037-915b-cbae269743f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/ico/close.gif</value>
      <webElementGuid>9c67f728-560f-40e9-9204-9e66408b6724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>e767ee7e-d79e-4dbd-8e0f-0a2a48eba84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserBox&quot;)/div[@class=&quot;drag-handle&quot;]/div[@class=&quot;drag-controls&quot;]/img[2]</value>
      <webElementGuid>2517fd2c-ea85-43f6-8a17-1d99bb3421ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UserBox']/div/div/img[2]</value>
      <webElementGuid>dbefc466-76d0-4dca-91c3-a273b405891a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Close']</value>
      <webElementGuid>d97f039c-4762-492f-8962-1cefe64f7020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>6f4e4ad0-5244-474f-91ab-96d706915467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/ico/close.gif' and @title = 'Close']</value>
      <webElementGuid>520f4a43-b678-4b83-bbed-431aebeb70a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
