<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close_send_for_review</name>
   <tag></tag>
   <elementGuidId>d3557e4e-7633-45b0-be3d-dcfbaced73ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Button0&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Button0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9861ad58-281d-43bc-a00d-fe8a0510f870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>50751588-360c-4ed2-8bdb-b46917529714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Button0</value>
      <webElementGuid>30bf15bd-7707-4ac5-863c-8a6dde66505b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>abbeefe0-c890-403b-a016-a1e92b69b0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e8ba9370-a87b-46e3-8320-d6178406987b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return ReloadParentWindow();</value>
      <webElementGuid>3f4f86da-9468-478f-b10f-0d48e0f2cf14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pnlMsgSent&quot;)/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;default b4ageingborder&quot;]/tbody[1]/tr[3]/td[1]/input[@class=&quot;button&quot;]</value>
      <webElementGuid>2725770c-2363-403f-9517-f7e1c7f4b07c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe_Send for Review__iframe-Review (1)</value>
      <webElementGuid>9b15064c-5b67-4c79-9e6c-8f4a40f6580b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Button0']</value>
      <webElementGuid>7775cbd5-a2ac-4505-96ce-fe221d916b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pnlMsgSent']/table/tbody/tr/td/table/tbody/tr[3]/td/input</value>
      <webElementGuid>aae79efe-f6a2-494d-85ec-9154572bd1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>688ae080-4a0f-4c4b-bea7-81fec9be1bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'Button0']</value>
      <webElementGuid>b7dbb935-057d-464d-a665-b731f31b5e7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
