<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close_change_auditor</name>
   <tag></tag>
   <elementGuidId>f6e8bff2-bc5d-43e7-869f-671bb3bcf071</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Button0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Button0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8202cd2e-aee3-4512-9a6b-f15db4381532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04e3c02f-e79d-4133-9ba0-4031c175fcc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Button0</value>
      <webElementGuid>4fe1bcb0-c1f9-4ca1-b39f-1043859a5588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>61cb84cb-3d7d-4f88-8222-978f88fcc4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af46c76c-994a-4076-a4d6-c8cebe05082d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return ReloadParentWindow();</value>
      <webElementGuid>e3e6d5b3-9497-4485-96ef-273b03d6eff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pnlMsgSent&quot;)/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;default b4ageingborder&quot;]/tbody[1]/tr[3]/td[1]/input[@class=&quot;button&quot;]</value>
      <webElementGuid>6dbb11da-9c11-45ba-91e9-17bfcceca01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe_Send for Review__iframe-Review</value>
      <webElementGuid>e8cdf404-1d18-40bb-b858-4cdf40155d50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Button0']</value>
      <webElementGuid>66703fcb-f277-4c5d-b26f-30f5ca8a5bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pnlMsgSent']/table/tbody/tr/td/table/tbody/tr[3]/td/input</value>
      <webElementGuid>72cfdaf8-a301-48ed-b669-107cd7007249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>0c949507-1d5f-4e55-bb2e-aabbd1bb0f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'Button0']</value>
      <webElementGuid>9304dbe1-82fc-4048-b8ee-3f3b98a4b3ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
