<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete_audit_icon</name>
   <tag></tag>
   <elementGuidId>a9c661e1-64d3-437f-baf0-bee503514101</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgDeleteAudit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgDeleteAudit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cd1071a-5253-4af4-80cd-2d44939719f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>c7d6ab23-6e33-42f6-8624-f769572745ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$gvSchQAudit$ctl02$imgDeleteAudit</value>
      <webElementGuid>dfb7f226-7bd7-4040-8135-74782b33ca3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgDeleteAudit</value>
      <webElementGuid>10fa3b8b-3f3b-4710-ad06-713738817acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>f614efac-3b1c-424f-b5e7-dd1df6cb845e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/ico/delete.gif</value>
      <webElementGuid>1dd3a91d-52fa-48ec-816d-3679242bc1db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgDeleteAudit&quot;)</value>
      <webElementGuid>b8540ccf-9c4f-4eb2-91e4-639f7527128f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgDeleteAudit']</value>
      <webElementGuid>580c0502-e41a-4135-9592-2ea34e7bb8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='demoTable']/tbody/tr[2]/td[11]/input[3]</value>
      <webElementGuid>9ff67f40-78bb-4d00-bbbb-0f363b063213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/input[3]</value>
      <webElementGuid>8d49e7f7-f4f7-4167-b7ab-ea3cfd398913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$gvSchQAudit$ctl02$imgDeleteAudit' and @id = 'ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgDeleteAudit' and @title = 'Delete' and @src = 'images/ico/delete.gif']</value>
      <webElementGuid>6208bd1c-d1bb-497d-b57f-ec8a069189fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
