<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>done_button</name>
   <tag></tag>
   <elementGuidId>d4e3709b-0470-4673-92ee-0eb32be5bc1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Submit2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Submit2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e9c8557-5861-420f-9e75-910209d7d2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Submit2</value>
      <webElementGuid>13cc273f-64c9-4707-b655-ea94c5a76b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>92bb2e68-e38f-4309-84d9-af390dd9e279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7cea0540-eb20-43dd-95d5-5eea879ba465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>3a36b049-694e-49bb-b55c-532f6c7c3e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return setValue()</value>
      <webElementGuid>b3c6c30a-2e11-4f5e-8f1a-d84131bb4bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TR_Multiple&quot;)/td[1]/table[@class=&quot;default&quot;]/tbody[1]/tr[2]/td[1]/input[@class=&quot;button&quot;]</value>
      <webElementGuid>fbb4bb14-3e49-4caa-8416-6ba394505c42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Submit2']</value>
      <webElementGuid>baf662a0-f643-469a-9ac8-79e317578c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='TR_Multiple']/td/table/tbody/tr[2]/td/input</value>
      <webElementGuid>d64e6bc9-8fe5-4d73-8dbd-2760e362da3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/table/tbody/tr[2]/td/input</value>
      <webElementGuid>6e037300-88d7-4c87-99b7-3f94a3d0de05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Submit2' and @type = 'button']</value>
      <webElementGuid>7766c958-4e82-4bf3-bc39-9bea505a3098</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
