<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drop_audit_icon</name>
   <tag></tag>
   <elementGuidId>5d18a3fc-d6ba-4ef8-bfc3-d57124a6dbd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgDropAudit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgDropAudit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23b0794b-c0fd-4e5d-8e65-a1a450d324a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>96233882-093c-40b6-b0a6-13a0d7b46c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$gvSchQAudit$ctl02$imgDropAudit</value>
      <webElementGuid>95e0a681-bd1e-4d11-ab72-a171b81bd1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgDropAudit</value>
      <webElementGuid>a65dc60b-7d52-493a-b6de-401a844f9363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>It will drop this Audit Area from current financial years Annual Audit Plan.</value>
      <webElementGuid>1341ac36-b346-4b97-8143-3af5aaf86855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/ico/drop.png</value>
      <webElementGuid>c1d23f62-5279-4c70-a802-90c6ce804a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgDropAudit&quot;)</value>
      <webElementGuid>018d750b-a738-4556-9378-392c6444b5bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgDropAudit']</value>
      <webElementGuid>2c39797c-7da2-4b59-9b36-9f7a3fcc066d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='demoTable']/tbody/tr[2]/td[11]/input[2]</value>
      <webElementGuid>c09c1268-5f98-4dcf-b0c3-c982f2e02922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/input[2]</value>
      <webElementGuid>e68ad3a7-35fd-4ea7-a21a-79d905c6aa8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$gvSchQAudit$ctl02$imgDropAudit' and @id = 'ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgDropAudit' and @title = 'It will drop this Audit Area from current financial years Annual Audit Plan.' and @src = 'images/ico/drop.png']</value>
      <webElementGuid>21934f3d-afe6-4eb1-993e-3dbfe72ce972</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
