<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>empID</name>
   <tag></tag>
   <elementGuidId>8ddcacc7-a7df-4447-bee4-e73b953dd744</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#empID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47f0fbbd-4a6a-490d-a515-b8c483e3e0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>empID</value>
      <webElementGuid>e388370f-24c3-43a8-86e9-411d0aa4703a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2661ca9-4f46-403c-8183-cc78189229ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empID</value>
      <webElementGuid>fb502e6c-2a27-4750-ae0b-7466ff321fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box</value>
      <webElementGuid>19022d90-e6a4-4edc-afc9-c077f8d0042c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return RestrictSqlInjection(event)</value>
      <webElementGuid>a4770457-b9ad-4e8c-8b43-249a424788c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empID&quot;)</value>
      <webElementGuid>ae5b3a96-247c-4b5a-a0ab-ae17ba54f70c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empID']</value>
      <webElementGuid>cec3fc30-75a9-4489-b034-9b9a0180eb40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pnlFilter']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>7e001a33-e1b2-4b7c-8675-8dfdf4e2b1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>e4219980-0824-4fb8-8931-ec68b451a92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'empID' and @type = 'text' and @id = 'empID']</value>
      <webElementGuid>a32a687d-1f9b-43d5-9435-baec6d5e73af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
