<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>filter_button_notification</name>
   <tag></tag>
   <elementGuidId>0917ca6c-0fc3-4ce1-b01d-61efe1c2370b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_ucWFNotifications_btnFilter0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_ucWFNotifications_btnFilter0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7aad2705-47fc-414a-9c20-155c98195479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>612c66e1-8185-4e5e-a314-f0a87e92a7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ucWFNotifications$btnFilter0</value>
      <webElementGuid>635300f6-0699-4e8b-a0c7-bf9dd55994b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Filter</value>
      <webElementGuid>76815490-4a33-44d8-b74d-bbb852479928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return Validate();</value>
      <webElementGuid>0437656e-1c22-426c-9c72-9b38eac336ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_ucWFNotifications_btnFilter0</value>
      <webElementGuid>5cee6a19-fc44-4924-bd7f-a834fdd46933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc3f957f-266c-4c4a-9819-6624a7b51f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_ucWFNotifications_btnFilter0&quot;)</value>
      <webElementGuid>22856d85-1a93-488e-986d-79df3c1ce8bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_ucWFNotifications_btnFilter0']</value>
      <webElementGuid>3a9ac8e6-ad88-4f00-bfbd-86c32d01b270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_ucWFNotifications_pnlFilter']/div/table/tbody/tr[4]/td[6]/input</value>
      <webElementGuid>119d8581-bf6e-4b3e-b275-af013a67b2d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[6]/input</value>
      <webElementGuid>d8ccad20-c6c1-416f-87f7-31257dab2be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder1$ucWFNotifications$btnFilter0' and @id = 'ctl00_ContentPlaceHolder1_ucWFNotifications_btnFilter0']</value>
      <webElementGuid>1ab7a094-804e-4d42-9751-b3cb2c7b0f42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
