<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Pick Auditee and Escalator__iframe-UserBox</name>
   <tag></tag>
   <elementGuidId>ad305de0-e508-461e-b6e7-75d8a26d6ea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//iframe[@name='_iframe-UserBox'])</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = '_iframe-UserBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;_iframe-UserBox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d60deae6-a37e-46f4-b058-02c24e54c61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>48b91d0d-66a6-4a41-b0f8-320f05e5d940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c3378efd-7a71-4819-9b75-78b28a861c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_iframe-UserBox</value>
      <webElementGuid>368eed29-f2c7-43eb-a20a-fb580f4f0ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserBox&quot;)/div[@class=&quot;drag-contentarea&quot;]/iframe[1]</value>
      <webElementGuid>f18ef192-efda-471c-b8c5-4a45d74e1188</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='_iframe-UserBox']</value>
      <webElementGuid>e947bc4b-9ea8-4794-9c5b-be5ed3767208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UserBox']/div[2]/iframe</value>
      <webElementGuid>48cd531d-9315-4a92-9464-f19315b85f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>665a0e6c-d586-4702-ae33-bddc1bfcd040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '_iframe-UserBox']</value>
      <webElementGuid>acaa7dda-5d6a-4e05-8b83-c288bd3a7f5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
