<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Tuesday, May 05, 2026 061650 PM__ifr_9ebf74</name>
   <tag></tag>
   <elementGuidId>0da04aee-227e-40a9-9e90-1f8a494a4367</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='_iframe-UserBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;_iframe-UserBox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e8613e75-c1a9-4a29-88f7-40a643c84e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>e9991cf0-42ca-4ef0-b4fd-38fa89bbce80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d8d5f4a6-f357-400e-b78b-a43066b33d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_iframe-UserBox</value>
      <webElementGuid>3a312237-ce17-4652-946d-d817513d2254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserBox&quot;)/div[@class=&quot;drag-contentarea&quot;]/iframe[1]</value>
      <webElementGuid>a9afbc1d-ced8-4011-8c81-7c69f213bca5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='_iframe-UserBox']</value>
      <webElementGuid>ad5ec9b1-cdbe-4e26-8962-58dbd0e4e1cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UserBox']/div[2]/iframe</value>
      <webElementGuid>06b5c7db-2c46-465f-93f4-f430937e80c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5ee92428-4adc-4198-ba4f-8d8488c0fffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '_iframe-UserBox']</value>
      <webElementGuid>7400332f-d1e6-4b72-a268-2bed7da59058</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
