<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Monday, May 04, 2026 123630 PM__ifra_899324</name>
   <tag></tag>
   <elementGuidId>19043e30-9873-4707-8b99-8f308d67b8a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='_iframe-UserBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;_iframe-UserBox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a8f8f1ee-6796-48ff-9ff8-1ac875eef654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>343b5c57-28b4-40a9-9fd7-f741cb23de71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>914fcfc7-6972-4acc-a3f5-7c2d6a8824f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_iframe-UserBox</value>
      <webElementGuid>792b2d25-46d0-4646-be0f-2b5ed19c763b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserBox&quot;)/div[@class=&quot;drag-contentarea&quot;]/iframe[1]</value>
      <webElementGuid>c107447a-bffe-49f6-8f86-b3cded51b313</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='_iframe-UserBox']</value>
      <webElementGuid>8c98dd3e-dfeb-44de-9cab-257829f054dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UserBox']/div[2]/iframe</value>
      <webElementGuid>731f0041-02ff-4739-849f-b77438778a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>962c6a40-4517-4bd6-8cc3-50dafe226672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '_iframe-UserBox']</value>
      <webElementGuid>28a31eaa-48be-4840-b5ca-1da988cb00be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
