<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Planned Days__iframe-UserBox</name>
   <tag></tag>
   <elementGuidId>e2164f84-0a2b-4618-a3ae-352451e29e6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='_iframe-UserBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;_iframe-UserBox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>72a3baf6-f003-4bd8-ac9b-95ed03b5fdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>553e66cb-5931-48d1-8a6f-c0405b5ed8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2858806b-24ce-4fa9-9f1d-41fe12dd29c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_iframe-UserBox</value>
      <webElementGuid>e5c4f842-bd78-486b-adff-d498de944e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserBox&quot;)/div[@class=&quot;drag-contentarea&quot;]/iframe[1]</value>
      <webElementGuid>c8455638-f813-4f35-9b6f-1d01ea812795</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='_iframe-UserBox']</value>
      <webElementGuid>d707a3d8-3c08-4f7c-a8d3-fd4b0c626b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UserBox']/div[2]/iframe</value>
      <webElementGuid>1c1cca8b-45bc-4c11-9ba7-96938dd7f63d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>bccdfed2-a485-4bc0-841e-aac2bc1edff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '_iframe-UserBox']</value>
      <webElementGuid>0e1aac57-45ee-4c8e-9f8d-822f4199a351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
