<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>import_btn_view_modify_annual_audit_plan</name>
   <tag></tag>
   <elementGuidId>713bc309-95fc-4ce4-9ce1-0f39c052dffb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_btnImport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_btnImport</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab89e5b1-4189-4ce1-98ac-89163eb097f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3a99f793-4f1b-4f43-94a8-35962063698b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$btnImport</value>
      <webElementGuid>ac7e47d3-de37-4354-a4d9-d66ef26ed547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Import</value>
      <webElementGuid>fce21552-1fcf-4e7b-b4e0-55c002cb4ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return ImportModifyAnualPlan('2026 - 2027','Q1','','1','5','','','','','','','','');</value>
      <webElementGuid>f3307f14-713b-4403-acfc-6bbd0eb95844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_btnImport</value>
      <webElementGuid>87762d00-fbba-4007-b10e-41ca85074b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a4e40194-d3f5-443c-a645-5127e2ea75cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_btnImport&quot;)</value>
      <webElementGuid>c7b02213-c7ff-434a-8d28-0e9b39058ca6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_btnImport']</value>
      <webElementGuid>4c6b17ef-4b99-430e-909c-526b1c00eb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/table/tbody/tr/td/table/tbody/tr[3]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr[3]/td/table/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>9cd1344c-c2af-46c2-bbb7-dd1b9b387e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>ea1c7ba3-d281-4aaa-9a87-6929cddc1120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder1$btnImport' and @id = 'ctl00_ContentPlaceHolder1_btnImport']</value>
      <webElementGuid>7e439ea3-0077-40db-87c1-31c9715e8b5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
