<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>no_of_times</name>
   <tag></tag>
   <elementGuidId>b46e6282-c6a5-42b5-a631-6fad94e944fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_gvAuditPlan_ctl04_txtNoTimesAudit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_gvAuditPlan_ctl04_txtNoTimesAudit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0abb896a-c9cc-4c93-a552-95cc5aef61cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$gvAuditPlan$ctl04$txtNoTimesAudit</value>
      <webElementGuid>34bc5c2a-1870-4c51-b09e-c73aaf04d4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d78b359-09fa-4c48-a78e-1f0afc8fd1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>310f7277-70c6-4628-8b26-f03bbf48ec0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>45ecb51d-c858-4a8e-b86b-e4a31b224d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_gvAuditPlan_ctl04_txtNoTimesAudit</value>
      <webElementGuid>c9d5ac37-fb0b-4ccc-98f4-cf6f689b46c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box</value>
      <webElementGuid>067375f3-8355-40de-8d6c-8eb401de1fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return NumberOnly(event)</value>
      <webElementGuid>4456144c-b00f-4a4a-915a-4c6885d264d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_gvAuditPlan_ctl04_txtNoTimesAudit&quot;)</value>
      <webElementGuid>1d822255-db04-4856-8a5c-729d609293d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_gvAuditPlan_ctl04_txtNoTimesAudit']</value>
      <webElementGuid>cdc71c32-e7e5-46ce-8f4e-18ef1f361dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='demoTable1']/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>6cb8880d-7193-4757-acf0-860a42f4c395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>90b2c1a9-db7d-486d-8335-da6eb0c58f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$gvAuditPlan$ctl04$txtNoTimesAudit' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder1_gvAuditPlan_ctl04_txtNoTimesAudit']</value>
      <webElementGuid>743abfce-b5a7-4446-aeb3-26a0dcfe3764</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
