<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NoDays_auditor</name>
   <tag></tag>
   <elementGuidId>7ddf4a03-8775-4de5-9d04-64ef0a6afeaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvUsers_ctl02_txtNoDays']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvUsers_ctl02_txtNoDays</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d99b3f5-4065-4f33-a73f-60911ebf4414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvUsers$ctl02$txtNoDays</value>
      <webElementGuid>f25ac392-ae63-4fc4-9157-a198050cea21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b11560dd-ecda-43af-9ad2-3956f2229d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>daf7bc9e-5af4-42a5-976a-d1b47495fe88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvUsers_ctl02_txtNoDays</value>
      <webElementGuid>73e8440a-070d-4334-bab6-61391c061252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box</value>
      <webElementGuid>085f3a4e-9de5-4ab7-bf16-0abf0a91d065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvUsers_ctl02_txtNoDays&quot;)</value>
      <webElementGuid>43742562-bed8-428a-be18-5a0aa4b507bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe_Planned Days__iframe-UserBox</value>
      <webElementGuid>118a2eba-0226-441e-bd85-cc3e5c6453e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvUsers_ctl02_txtNoDays']</value>
      <webElementGuid>6118a4a6-8131-45ae-ae39-90ee9242a27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvUsers']/tbody/tr/td[2]/input</value>
      <webElementGuid>151695dd-64d8-46fc-9ba6-c6911a2c13a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>bdc147c0-12bd-4db7-8bba-590f85caffd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'gvUsers$ctl02$txtNoDays' and @type = 'text' and @id = 'gvUsers_ctl02_txtNoDays']</value>
      <webElementGuid>6b7eb36c-dcd4-4733-bda8-7ab72335a8dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
