<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NoDays_reviewer</name>
   <tag></tag>
   <elementGuidId>e7faa14f-b3ec-47ba-adb1-fefef3c42a10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvUsers_ctl03_txtNoDays']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvUsers_ctl03_txtNoDays</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f0507fb-af41-459f-83cf-215290b0a7b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvUsers$ctl03$txtNoDays</value>
      <webElementGuid>4c79bb86-87f7-4592-8a6c-320c5d406ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db56a716-ef2e-47b8-88c9-01871dbb7869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>6a9a869c-cd85-4050-9758-195e615d8d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvUsers_ctl03_txtNoDays</value>
      <webElementGuid>85fb2fcb-be4a-4a99-ae54-89b9ab2e24bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box</value>
      <webElementGuid>7cd55a9a-dfca-4ff6-8d9a-9d90a810e88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvUsers_ctl03_txtNoDays&quot;)</value>
      <webElementGuid>1e451400-afc3-42f2-8978-78bb2905f23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe_Planned Days__iframe-UserBox</value>
      <webElementGuid>b27d699d-a8b2-4891-b9ba-46f387fb6d3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvUsers_ctl03_txtNoDays']</value>
      <webElementGuid>955b4703-4cac-44c5-8d71-61c415ced0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvUsers']/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>8c152d8f-fc7f-4818-8968-7602e9b8fc31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>c7a71fe2-dc10-48ab-9824-1c580e0acbce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'gvUsers$ctl03$txtNoDays' and @type = 'text' and @id = 'gvUsers_ctl03_txtNoDays']</value>
      <webElementGuid>f1c3641f-0837-4c4d-9d43-e0975f093a0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
