<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Notifications</name>
   <tag></tag>
   <elementGuidId>f8a5ffe1-a74a-43b1-969c-960248d0c955</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Stm0p4i1eTX > table.FMenu > tbody > tr > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//font[@id='Stm0p4i1eTX']/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>41a584e9-0b43-4353-b11c-6f3eb9b11cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notifications</value>
      <webElementGuid>c630b557-25cc-483a-93ce-d7f85ddd5efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Stm0p4i1eTX&quot;)/table[@class=&quot;FMenu&quot;]/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>9476c8a6-34f6-4a57-ad3c-22cec6168f0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//font[@id='Stm0p4i1eTX']/table/tbody/tr/td</value>
      <webElementGuid>fc7ca1c7-4cc4-4d4b-a3fb-cacbfe7e5250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve Master'])[1]/following::td[3]</value>
      <webElementGuid>e683a5cf-fd4c-4ad0-b17b-d2b4c4c7639f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Request Tracker'])[1]/following::td[8]</value>
      <webElementGuid>99e39bee-803e-4983-989e-dfb58fde7351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status of Annual Audit Plan'])[1]/preceding::td[1]</value>
      <webElementGuid>abb16e9e-7957-40da-acfd-ff8b0e638939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annual Audit Plan'])[1]/preceding::td[5]</value>
      <webElementGuid>9e8346b2-a353-4c8a-a48f-3e8cc462ae25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Notifications']/parent::*</value>
      <webElementGuid>a79a03e7-d1f1-43ad-8f7e-babc3346fe1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/table/tbody/tr/td/table/tbody/tr[2]/td/a/div/table/tbody/tr/td/font/table/tbody/tr/td</value>
      <webElementGuid>b9689cb8-fa75-4c29-95f2-8501f37a8d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Notifications' or . = 'Notifications')]</value>
      <webElementGuid>3772c115-5cde-4b11-91e5-beeb91f6eadf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
