<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_button_auditors_workspace</name>
   <tag></tag>
   <elementGuidId>cebed2d8-4098-49f8-8492-aaacd47dd3ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_DList_ctl00_GVData_ctl02_optAudit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_DList_ctl00_GVData_ctl02_optAudit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ceccf204-5b94-441a-b0a5-d031663c034d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_DList_ctl00_GVData_ctl02_optAudit</value>
      <webElementGuid>c38db08a-0e68-482c-9daf-4daada62c9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>408d893f-7e92-4872-806f-b9ed6985bc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$DList$ctl00$GVData$ctl02$optAudit</value>
      <webElementGuid>38cfc439-9091-4fb5-b00d-38f52061e096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>optAudit</value>
      <webElementGuid>a300151f-b22a-491a-a9cc-3326a92e6e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$ContentPlaceHolder1$DList$ctl00$GVData$ctl02$optAudit\',\'\')', 0)</value>
      <webElementGuid>2b1dc969-2002-47db-808f-30df1632080c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_DList_ctl00_GVData_ctl02_optAudit&quot;)</value>
      <webElementGuid>8d58884d-6abf-41b4-991d-57b0dc4d61dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_DList_ctl00_GVData_ctl02_optAudit']</value>
      <webElementGuid>de8463b9-c514-4df0-ad07-db58dbbed52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_DList_ctl00_GVData']/tbody/tr[2]/td/span/input</value>
      <webElementGuid>d175f3ac-f9f6-49c5-99cf-cc09acb3c94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[2]/td/span/input</value>
      <webElementGuid>3e81875a-4c50-4236-a275-64c314dcd681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_ContentPlaceHolder1_DList_ctl00_GVData_ctl02_optAudit' and @type = 'radio' and @name = 'ctl00$ContentPlaceHolder1$DList$ctl00$GVData$ctl02$optAudit']</value>
      <webElementGuid>ee044714-3df9-4918-b21a-b825c5b016f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
