<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>re_activate_audit</name>
   <tag></tag>
   <elementGuidId>e571e464-5d93-4b72-b9bb-7d9245f74949</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgReActivateAudit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgReActivateAudit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15afaea2-5a0a-4de5-a6f0-48d2c11836db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>2690d3b8-cc04-4171-989b-1e270b575cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$gvSchQAudit$ctl02$imgReActivateAudit</value>
      <webElementGuid>018a8cc6-5744-40f1-996e-7ee83a91b495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgReActivateAudit</value>
      <webElementGuid>705f7996-b29f-46c7-8981-75b47bac3049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>It will re-activate audit area</value>
      <webElementGuid>14d3729e-076d-4fdc-aee3-461da0544a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/ico/undrop.png</value>
      <webElementGuid>180c69bd-c545-4d8e-a41f-b74bc9d2aa44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgReActivateAudit&quot;)</value>
      <webElementGuid>0db49f5b-b880-4562-8688-c77b9c051782</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgReActivateAudit']</value>
      <webElementGuid>62e03502-1266-4b13-9b60-b1521eb56e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='demoTable']/tbody/tr[2]/td[11]/input</value>
      <webElementGuid>32bcdfbd-d852-4a93-a297-12ca9cacde04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/input</value>
      <webElementGuid>6c54bd06-8769-496f-b948-4c7f44695824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$gvSchQAudit$ctl02$imgReActivateAudit' and @id = 'ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_imgReActivateAudit' and @title = 'It will re-activate audit area' and @src = 'images/ico/undrop.png']</value>
      <webElementGuid>a8174f4d-b95a-471b-951f-cb3672450d62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
