<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_sbu_audit_area</name>
   <tag></tag>
   <elementGuidId>894df022-17e6-4a02-939c-6e9aaa39ee5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_lstSBU</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ctl00_ContentPlaceHolder1_lstSBU']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>18b8a3a4-cef1-4087-b163-55b7a63bed27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>62fb9fd0-8784-45ca-bb7e-c77ec242e933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$lstSBU</value>
      <webElementGuid>b7c8ad00-8e85-4393-8b06-068657979242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>f07a5ca3-90d4-4164-921c-49721b67033b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_lstSBU</value>
      <webElementGuid>53803c59-dde2-4e3d-97fb-72f84fc74ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>return selectAllOptions('ctl00_ContentPlaceHolder1_lstSBU');</value>
      <webElementGuid>bb91ca65-7e88-4a8a-9f0d-c6902abb5efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	All
	Aditya Birla Capital Limited
	Aditya Birla Finance Limited
	Coordinator
	HR-1
	IT -1
	IT-1
	Qa
	Qa dept
	Qa1
	sbu_a
	sbu_b
	sbu_c
	sbu_d
	sbu_e
	sbu_g
	sbu_name10
	sbu_name100
	sbu_name11
	sbu_name12
	sbu_name13
	sbu_name14
	sbu_name15
	sbu_name16
	sbu_name17
	sbu_name18
	sbu_name19
	sbu_name2
	sbu_name20
	sbu_name21
	sbu_name22
	sbu_name23
	sbu_name24
	sbu_name25
	sbu_name26
	sbu_name27
	sbu_name28
	sbu_name29
	sbu_name3
	sbu_name30
	sbu_name31
	sbu_name32
	sbu_name33
	sbu_name34
	sbu_name35
	sbu_name36
	sbu_name37
	sbu_name38
	sbu_name39
	sbu_name4
	sbu_name40
	sbu_name41
	sbu_name42
	sbu_name43
	sbu_name44
	sbu_name45
	sbu_name46
	sbu_name47
	sbu_name48
	sbu_name49
	sbu_name5
	sbu_name50
	sbu_name51
	sbu_name52
	sbu_name53
	sbu_name54
	sbu_name55
	sbu_name56
	sbu_name57
	sbu_name58
	sbu_name59
	sbu_name6
	sbu_name60
	sbu_name61
	sbu_name62
	sbu_name63
	sbu_name64
	sbu_name65
	sbu_name66
	sbu_name67
	sbu_name68
	sbu_name69
	sbu_name7
	sbu_name70
	sbu_name71
	sbu_name72
	sbu_name73
	sbu_name74
	sbu_name75
	sbu_name76
	sbu_name77
	sbu_name78
	sbu_name79
	sbu_name8
	sbu_name80
	sbu_name81
	sbu_name82
	sbu_name83
	sbu_name84
	sbu_name85
	sbu_name86
	sbu_name87
	sbu_name88
	sbu_name89
	sbu_name9
	sbu_name90
	sbu_name91
	sbu_name92
	sbu_name93
	sbu_name94
	sbu_name95
	sbu_name96
	sbu_name97
	sbu_name98
	sbu_name99
	sbu_p
	sbu_q
	sbu_s
	sbu_t
	sbusss_name1
	Support
	Test Sbu 1
	Test Sbu 2
	TESTSBU

</value>
      <webElementGuid>44d77248-3e02-4c08-a60a-7ace2a53a74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_lstSBU&quot;)</value>
      <webElementGuid>021c1759-0431-4544-88ad-fbf86d813536</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ctl00_ContentPlaceHolder1_lstSBU']</value>
      <webElementGuid>4cad0837-dfda-4cf8-b189-1ac3f6c22ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/table/tbody/tr/td/table/tbody/tr[3]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[3]/td[2]/select</value>
      <webElementGuid>f9e9fc11-51ec-4e48-ad82-56bb35557752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audit SBU:'])[1]/following::select[1]</value>
      <webElementGuid>67bcb5c9-0880-4f36-8ce6-f05e2a1f9810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>48ca73f3-2935-425e-bd42-a686ceae2ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note: Ctr. + click to select / deselect multiple selection.'])[1]/preceding::select[1]</value>
      <webElementGuid>e57f5e98-cc98-4922-b984-33ceaf4300a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>cf1eaa28-0362-45fd-9d2c-aee2679c10ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/select</value>
      <webElementGuid>e6badaa3-d580-4482-a257-388c31c6f954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$ContentPlaceHolder1$lstSBU' and @id = 'ctl00_ContentPlaceHolder1_lstSBU' and (text() = '
	All
	Aditya Birla Capital Limited
	Aditya Birla Finance Limited
	Coordinator
	HR-1
	IT -1
	IT-1
	Qa
	Qa dept
	Qa1
	sbu_a
	sbu_b
	sbu_c
	sbu_d
	sbu_e
	sbu_g
	sbu_name10
	sbu_name100
	sbu_name11
	sbu_name12
	sbu_name13
	sbu_name14
	sbu_name15
	sbu_name16
	sbu_name17
	sbu_name18
	sbu_name19
	sbu_name2
	sbu_name20
	sbu_name21
	sbu_name22
	sbu_name23
	sbu_name24
	sbu_name25
	sbu_name26
	sbu_name27
	sbu_name28
	sbu_name29
	sbu_name3
	sbu_name30
	sbu_name31
	sbu_name32
	sbu_name33
	sbu_name34
	sbu_name35
	sbu_name36
	sbu_name37
	sbu_name38
	sbu_name39
	sbu_name4
	sbu_name40
	sbu_name41
	sbu_name42
	sbu_name43
	sbu_name44
	sbu_name45
	sbu_name46
	sbu_name47
	sbu_name48
	sbu_name49
	sbu_name5
	sbu_name50
	sbu_name51
	sbu_name52
	sbu_name53
	sbu_name54
	sbu_name55
	sbu_name56
	sbu_name57
	sbu_name58
	sbu_name59
	sbu_name6
	sbu_name60
	sbu_name61
	sbu_name62
	sbu_name63
	sbu_name64
	sbu_name65
	sbu_name66
	sbu_name67
	sbu_name68
	sbu_name69
	sbu_name7
	sbu_name70
	sbu_name71
	sbu_name72
	sbu_name73
	sbu_name74
	sbu_name75
	sbu_name76
	sbu_name77
	sbu_name78
	sbu_name79
	sbu_name8
	sbu_name80
	sbu_name81
	sbu_name82
	sbu_name83
	sbu_name84
	sbu_name85
	sbu_name86
	sbu_name87
	sbu_name88
	sbu_name89
	sbu_name9
	sbu_name90
	sbu_name91
	sbu_name92
	sbu_name93
	sbu_name94
	sbu_name95
	sbu_name96
	sbu_name97
	sbu_name98
	sbu_name99
	sbu_p
	sbu_q
	sbu_s
	sbu_t
	sbusss_name1
	Support
	Test Sbu 1
	Test Sbu 2
	TESTSBU

' or . = '
	All
	Aditya Birla Capital Limited
	Aditya Birla Finance Limited
	Coordinator
	HR-1
	IT -1
	IT-1
	Qa
	Qa dept
	Qa1
	sbu_a
	sbu_b
	sbu_c
	sbu_d
	sbu_e
	sbu_g
	sbu_name10
	sbu_name100
	sbu_name11
	sbu_name12
	sbu_name13
	sbu_name14
	sbu_name15
	sbu_name16
	sbu_name17
	sbu_name18
	sbu_name19
	sbu_name2
	sbu_name20
	sbu_name21
	sbu_name22
	sbu_name23
	sbu_name24
	sbu_name25
	sbu_name26
	sbu_name27
	sbu_name28
	sbu_name29
	sbu_name3
	sbu_name30
	sbu_name31
	sbu_name32
	sbu_name33
	sbu_name34
	sbu_name35
	sbu_name36
	sbu_name37
	sbu_name38
	sbu_name39
	sbu_name4
	sbu_name40
	sbu_name41
	sbu_name42
	sbu_name43
	sbu_name44
	sbu_name45
	sbu_name46
	sbu_name47
	sbu_name48
	sbu_name49
	sbu_name5
	sbu_name50
	sbu_name51
	sbu_name52
	sbu_name53
	sbu_name54
	sbu_name55
	sbu_name56
	sbu_name57
	sbu_name58
	sbu_name59
	sbu_name6
	sbu_name60
	sbu_name61
	sbu_name62
	sbu_name63
	sbu_name64
	sbu_name65
	sbu_name66
	sbu_name67
	sbu_name68
	sbu_name69
	sbu_name7
	sbu_name70
	sbu_name71
	sbu_name72
	sbu_name73
	sbu_name74
	sbu_name75
	sbu_name76
	sbu_name77
	sbu_name78
	sbu_name79
	sbu_name8
	sbu_name80
	sbu_name81
	sbu_name82
	sbu_name83
	sbu_name84
	sbu_name85
	sbu_name86
	sbu_name87
	sbu_name88
	sbu_name89
	sbu_name9
	sbu_name90
	sbu_name91
	sbu_name92
	sbu_name93
	sbu_name94
	sbu_name95
	sbu_name96
	sbu_name97
	sbu_name98
	sbu_name99
	sbu_p
	sbu_q
	sbu_s
	sbu_t
	sbusss_name1
	Support
	Test Sbu 1
	Test Sbu 2
	TESTSBU

')]</value>
      <webElementGuid>dc8bb83b-8c8d-4f8b-be4a-dd83e99dca51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
