<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>send_for_review</name>
   <tag></tag>
   <elementGuidId>7f441096-58bc-4e19-b89a-275663c1361e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSendForReview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnSendForReview']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>633d24a4-ccd4-48a8-808f-f95d289495f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>949342ab-29ce-4928-9f6e-5e28319451f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSendForReview</value>
      <webElementGuid>fbb20bf5-6b69-458f-9761-375ada3ae30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Send for Review</value>
      <webElementGuid>ea70e3e1-d343-48a3-b0c3-b8623b4e7650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return ValidateForm();</value>
      <webElementGuid>9352151d-f07f-4dde-bf86-0a2db48ac6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSendForReview</value>
      <webElementGuid>403e405c-6a64-4cba-83cd-84cecd01b02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87b17027-046c-4211-aee4-8f9e84f2386d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSendForReview&quot;)</value>
      <webElementGuid>8f059aac-e035-49fa-af2f-5076c2b781b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe_Send for Review__iframe-Review (1)</value>
      <webElementGuid>441d5bc2-97b9-48b0-84d2-603284672705</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnSendForReview']</value>
      <webElementGuid>146ba92c-84a7-4f05-8b33-9900653434fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pnlReview']/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>6c7a4151-7303-488f-8908-79c2772e521f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>60954412-ae0e-4266-924e-c44c7a60d7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnSendForReview' and @id = 'btnSendForReview']</value>
      <webElementGuid>150c0c2e-96d5-40b6-aa3a-ed685e816fa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
