<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>view_derails_icon</name>
   <tag></tag>
   <elementGuidId>2a71625b-1cdb-4437-8676-71c74700d20e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_aAuditLogs']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[title=&quot;View Audit Logs&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8d972dc6-6bad-416c-9823-8ae0609989f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View Audit Logs</value>
      <webElementGuid>877e24d6-4ff2-46e0-adea-15cb457be89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0b4e7487-a912-4d8b-a752-286a9adecd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/ico/page.gif</value>
      <webElementGuid>769e5b7a-1661-4fa4-a1a1-b7a40a4bb2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_aAuditLogs&quot;)/img[1]</value>
      <webElementGuid>9048fa28-26c7-4cc1-8b29-6640fb8f5b3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ContentPlaceHolder1_gvSchQAudit_ctl02_aAuditLogs']/img</value>
      <webElementGuid>ac2f00da-8370-4e55-925e-843d4cb1cc1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='View Audit Logs']</value>
      <webElementGuid>5c3be7f1-75a0-4115-816e-8bb6fb2ec266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/a/img</value>
      <webElementGuid>c652bc63-a74c-46da-8465-44beacd3bed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'View Audit Logs' and @src = 'images/ico/page.gif']</value>
      <webElementGuid>e18b8219-e8e8-4636-8c80-5239abe74ba6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
